name: lunar-e2e-pin-rotation-94f87df32
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened 94f87df32'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-94f87df32'
    runs-on: localdev-e2e-test-37629702757-1-github-2-e2e
    steps:
      - run: /bin/echo 'pin rotation CI 94f87df32'
